STORAGE_DIR = './face'

RECEIVED_SIGNAL = '1'
TRANSMITED_SUCCESS_SIGNAL = b'2'
TRANSMITED_FAIL_SIGNAL = b'3'
TRANSMITED_WRONG_CONFIG_SIGNAL = b'0'

PORT = 'COM1'
BAURATE = 9600
# PORT ='/dev/ttyAMA0'

HAAR_DIR = 'haarcascade_frontalface_default.xml'

TIMEOUT = 10

CAMERA_INDEX = 0